### ISSUE TITLE
Please clarify UpCloud relationship or security review status

### ISSUE THREAD

**Issue by james-nesbitt** [Jalle19/upcloud-go-sdk#25]
HI there, I'm considering using this library in an upcloud related provisioning tool, and wonder if you could clarify the following:

1. do you have any business connection with upcloud;
2. does upcloud offer any approval of/comment on your library;
3. have you had any security review of your product.

This is kind of all corp. BS, but the kind of questions that will come up in any serious evaluation.  

Your API has a pretty straight-forward implementation, and it seems clear how usernames and passwords are used (passed off to the hashicorp-http implementation) but you are consuming corproate authentication information (and have Public accessors defined for Passwords) so it is a necessary question.
 
J

**Comment by Jalle19** [comment]
Hi,

Thanks for showing interest, so far I've felt like I'm pretty much the only one to use this SDK.

> do you have any business connection with upcloud;

Not personally, but the company I work for are using their services. This is partly why I started working on this (we needed something like https://github.com/Jalle19/packer-builder-upcloud).

> does upcloud offer any approval of/comment on your library;

Yes, I was in contact with Jonathan Gabor (@jgabor) before I started working on this to make sure we weren't duplicating any efforts. They've offered me a free test account which the integration tests on Travis CI run against. They plugged it briefly on Twitter back when I did the initial release (https://twitter.com/upcloud/status/750659523363340288).

> have you had any security review of your product.

None whatsoever.

> Your API has a pretty straight-forward implementation, and it seems clear how usernames and passwords are used (passed off to the hashicorp-http implementation) but you are consuming corproate authentication information (and have Public accessors defined for Passwords) so it is a necessary question.

Is there anything in particular you'd like to see changed in this regard?

**Comment by james-nesbitt** [comment]
I have no targets for this.  Some corporate use of such libraries requires independenty security assessment, but it's not something that I am asking for.  If believe that most of the hashicorp stuff is externally tested (still checking that.)
What you might consider doing is detailing in the project README what code workflows use the authentication details; anyone looking at the project could quickly trace the path.
Making the password/username retreival functions internal might be a good idea, but that doesn't necessarily change anything.

I will probably use the library anyway, and will keep in touch about it.  I might submit a PR for a README clarification, but I am not a security expert.

**Comment by Jalle19** [comment]
Okay, I'll see what I can do.

**Comment by james-nesbitt** [comment]
this is not a standing issue, I will close it.
