### ISSUE TITLE
Does the library work with uses with 2FA enabled?

### ISSUE THREAD

**Issue by james-nesbitt** [Jalle19/upcloud-go-sdk#26]
Can you tell me if your library has been tested/used with user credentials that have 2-factor authentication enabled?

**Comment by james-nesbitt** [comment]
To clarify, I am using your library, and running the ./service/Service.GetServers(), using a client with credentials that I have just tested, and I get the following error:
(not error wrapping is from my lib, which uses logrus to pass back the library error)
````
ERRO[0000] Could not list UpCloud servers                error="Authentication failed using the given username and password. (AUTHENTICATION_FAILED)"
````

**Comment by james-nesbitt** [comment]
Ah, I apologize, I had obviously made a mistake in my tooling when passing credentials to the client.  When I hardcoded my credentials into the Client constructor, it worked.

Closing this issue.

**Comment by Jalle19** [comment]
I honestly haven't tried using the API with anything other than the main account credentials. I imagine 2FA is bypassed completely for the API.
